#include <iostream>
#include <thread>
#include <chrono>
#include <mutex>
#include <condition_variable>
#include <atomic>
#include <cstdlib>
#include <string>

// --- 4-State FSM 정의 ---
// 상태 천이도에 기반한 4가지 State 정의
enum class FSMState {
    STRONGLY_NOT_TAKEN,
    WEAKLY_NOT_TAKEN,
    WEAKLY_TAKEN,
    STRONGLY_TAKEN
};
// 일반 enum 과 enum class 로 하는 것에 무슨 차이가 있지? 일반 enum 이 코드가 더 깔끔할 것 같은데?


class PredictiveDVFS {
private:
    FSMState state = FSMState::WEAKLY_TAKEN; // 초기 상태 설정
    std::mutex mtx;
    bool early_scale = true;

public:
    // LLM 호출 여부 예측 (Taken 상태일 때 true 반환)
    bool predict() {
        std::lock_guard<std::mutex> lock(mtx);
        return (state == FSMState::WEAKLY_TAKEN || state == FSMState::STRONGLY_TAKEN);
    }

    // 미들웨어 결과에 따른 FSM 상태 업데이트[cite: 3]
    void update(bool is_hit) {
        std::lock_guard<std::mutex> lock(mtx);
        if (is_hit) {
            switch (state) {
                case FSMState::STRONGLY_NOT_TAKEN: state = FSMState::WEAKLY_NOT_TAKEN; break;
                case FSMState::WEAKLY_NOT_TAKEN:   state = FSMState::WEAKLY_TAKEN; break;
                case FSMState::WEAKLY_TAKEN:       state = FSMState::STRONGLY_TAKEN; break;
                case FSMState::STRONGLY_TAKEN:     state = FSMState::STRONGLY_TAKEN; break;
            }
            std::cout << "[FSM] Update: Hit (LLM Request Occurred) -> New State: " << stateToString(state) << "\n";
        } else {
            switch (state) {
                case FSMState::STRONGLY_TAKEN:     state = FSMState::WEAKLY_TAKEN; break;
                case FSMState::WEAKLY_TAKEN:       state = FSMState::WEAKLY_NOT_TAKEN; break;
                case FSMState::WEAKLY_NOT_TAKEN:   state = FSMState::STRONGLY_NOT_TAKEN; break;
                case FSMState::STRONGLY_NOT_TAKEN: state = FSMState::STRONGLY_NOT_TAKEN; break;
            }
            std::cout << "[FSM] Update: Miss (No LLM Request) -> New State: " << stateToString(state) << "\n";
        }
    }

    // vision model 한테 call 됨, state 는 controller 에서 판단함. 
    void scaleFrequencyEarly() {
        if (state == FSMState::STRONGLY_TAKEN || state == FSMState::WEAKLY_TAKEN) {
            // DVFS 시작
            early_scale = true;
        } else {
            early_scale = false;
            return;
        }
        std::cout << "[DVFS] Early Scaling Triggered (Predictive). Hiding 15ms latency...\n";
        std::cout << "[DVFS] GPU Frequency is now HIGH.\n";
    }
    
    // middle ware 한테 call 됨. 
    void scaleFrequencyReactive(bool is_hit) {
        if (!early_scale && is_hit) {
          // DVFS
        } // 이 경우의 수 이외에는 모두 continue
        
        update (is_hit);
        
        std::cout << "[DVFS] Reactive Scaling Triggered (Not Taken, but LLM requested). 15ms overhead penalty applied!\n";
        std::cout << "[DVFS] GPU Frequency is now HIGH.\n";
    }

    std::string stateToString(FSMState s) {
        switch (s) {
            case FSMState::STRONGLY_NOT_TAKEN: return "Strongly Not Taken";
            case FSMState::WEAKLY_NOT_TAKEN:   return "Weakly Not Taken";
            case FSMState::WEAKLY_TAKEN:       return "Weakly Taken";
            case FSMState::STRONGLY_TAKEN:     return "Strongly Taken";
            default: return "Unknown";
        }
    }
};

// --- 글로벌 객체 및 동기화 변수 ---
PredictiveDVFS dvfsController;
std::mutex llm_mtx;
std::condition_variable llm_cv;
bool llm_request_flag = false;
std::atomic<bool> system_running(true);

// --- 2. 미들웨어 (Robot Middleware) ---
// 오브젝트를 구분하여 LLM 모션 플래닝이 필요한지 결정하는 간단한 함수
bool robotMiddleware(int frame_count) {
    // 예시: 3번째 프레임마다 장애물이 감지되어 LLM 모션 플래닝을 요청한다고 가정
    if (frame_count % 3 == 0) {
        std::cout << "[Middleware] Object detected! Decided to request LLM.\n";
        return true;
    }
    std::cout << "[Middleware] Safe path. No LLM request needed.\n";
    return false;
}

// --- 3. LLM 스레드 (LLM Model) ---
void llmThreadFunc() {
    while (system_running) {
        std::unique_lock<std::mutex> lock(llm_mtx);
        llm_cv.wait(lock, [] { return llm_request_flag || !system_running; });
        
        if (!system_running) break;

        std::cout << "[LLM Thread] Starting LLM Inference...\n";
        
        // system() 함수를 통한 외부 바이너리 통째 호출
        // (실제 환경이 아니므로 echo로 대체 구동을 모사함, 실제로는 ./llama-cli 적용)
        int ret = system("echo 'Motion Plan Generated by llama-cli' > /dev/null");
        (void)ret; // unused variable 경고 무시
        
        std::cout << "[LLM Thread] LLM Output Completed.\n";
        llm_request_flag = false;
    }
}

// --- 1 & 4. 비전 스레드 (Vision Model) ---
void visionThreadFunc() {
    const int target_fps = 20;
    const int frame_duration_ms = 1000 / target_fps; // 50ms per frame
    
    for (int frame_count = 1; frame_count <= 10; ++frame_count) {
        auto start_time = std::chrono::steady_clock::now();
        std::cout << "\n=== Processing Frame " << frame_count << " ===\n";

        // a. 추론 시작 시 FSM 상태 확인 및 Predictive-DVFS 작동
        bool predicted_taken = dvfsController.predict();
        std::thread early_dvfs_thread;
        if (predicted_taken) {
            // 왼쪽 시퀀스 차트: Vision Inference 시작 시 비동기로 주파수 사전 승압
            early_dvfs_thread = std::thread(&PredictiveDVFS::scaleFrequencyEarly, &dvfsController);
        }

        // b. 비전 모델 추론 모사 (YOLOv8, DVFS 지연 15ms보다 긴 35ms로 모사하여 Latency 은닉)
        std::cout << "[Vision Thread] Vision Model Inference Started...\n";
        std::this_thread::sleep_for(std::chrono::milliseconds(35)); 
        std::cout << "[Vision Thread] Vision Output Generated.\n";

        // 예측 승압을 수행했다면 완료될 때까지 동기화 보장 (이미 35ms가 지났으므로 즉시 종료됨)
        if (early_dvfs_thread.joinable()) {
            early_dvfs_thread.join();
        }

        // c. 미들웨어를 통한 실제 LLM 호출 여부 결정
        bool actual_llm_request = robotMiddleware(frame_count);

        // d. FSM 상태 업데이트[cite: 3]
        dvfsController.update(actual_llm_request);

        // e. LLM 요청 처리 및 Reactive Scaling 대응
        if (actual_llm_request) {
            if (!predicted_taken) {
                // 예측이 틀렸을 경우 (Not Taken 예측 -> Hit 발생)[cite: 4] 오른쪽 시퀀스 차트
                dvfsController.scaleFrequencyReactive();
            }

            // LLM 스레드 깨우기
            {
                std::lock_guard<std::mutex> lock(llm_mtx);
                llm_request_flag = true;
            }
            llm_cv.notify_one();
            
            // LLM 처리가 끝날 때까지 대기하여 파이프라인 정합성 유지 (동기 모사)
            std::this_thread::sleep_for(std::chrono::milliseconds(20));
        }

        // f. 20FPS 유지를 위한 Sleep 보정
        auto end_time = std::chrono::steady_clock::now();
        auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(end_time - start_time).count();
        if (elapsed < frame_duration_ms) {
            std::this_thread::sleep_for(std::chrono::milliseconds(frame_duration_ms - elapsed));
        }
    }

    // 시스템 종료 트리거
    system_running = false;
    llm_cv.notify_all();
}

int main() {
    std::cout << "Starting VLA Predictive-DVFS Framework...\n";

    // 스레드 분리 실행
    std::thread llm_thread(llmThreadFunc);
    std::thread vision_thread(visionThreadFunc);

    vision_thread.join();
    llm_thread.join();

    std::cout << "System Terminated.\n";
    return 0;
}
