#include <iostream>
#include <thread>
#include <chrono>
#include <mutex>
#include <condition_variable>
#include <atomic>
#include <cstdlib>
#include <string>

enum FSMState {
    STRONGLY_NOT_TAKEN,
    WEAKLY_NOT_TAKEN,
    WEAKLY_TAKEN,
    STRONGLY_TAKEN
};

class PredictiveDVFS {
private:
    FSMState state = WEAKLY_TAKEN; 
    std::mutex mtx;
    bool early_scale = false;

    // 컨트롤러 state, mutex 갖고 있는 상태
    void update(bool is_hit) {
        if (is_hit) {
            switch (state) {
                case STRONGLY_NOT_TAKEN: state = WEAKLY_NOT_TAKEN; break;
                case WEAKLY_NOT_TAKEN:   state = WEAKLY_TAKEN; break;
                case WEAKLY_TAKEN:       state = STRONGLY_TAKEN; break;
                case STRONGLY_TAKEN:     state = STRONGLY_TAKEN; break;
            }
            std::cout << "[FSM] Update: Hit -> New State: " << stateToString(state) << "\n";
        } else {
            switch (state) {
                case STRONGLY_TAKEN:     state = WEAKLY_TAKEN; break;
                case WEAKLY_TAKEN:       state = WEAKLY_NOT_TAKEN; break;
                case WEAKLY_NOT_TAKEN:   state = STRONGLY_NOT_TAKEN; break;
                case STRONGLY_NOT_TAKEN: state = STRONGLY_NOT_TAKEN; break;
            }
            std::cout << "[FSM] Update: Miss -> New State: " << stateToString(state) << "\n";
        }
    }

    std::string stateToString(FSMState s) {
        switch (s) {
            case STRONGLY_NOT_TAKEN: return "Strongly Not Taken";
            case WEAKLY_NOT_TAKEN:   return "Weakly Not Taken";
            case WEAKLY_TAKEN:       return "Weakly Taken";
            case STRONGLY_TAKEN:     return "Strongly Taken";
            default: return "Unknown";
        }
    }

public:
    // Vision Model이 추론 시작 시 call
    void scaleFrequencyEarly() {
        std::lock_guard<std::mutex> lock(mtx);
        if (state == STRONGLY_TAKEN || state == WEAKLY_TAKEN) {
            early_scale = true;
            // DVFS
            std::cout << "[DVFS] Early Scaling Triggered (Predictive). Scaling asynchronously...\n";
        } else {
            early_scale = false;
        }
    }
    
    // Middleware가 추론 결과 구한 후 call
    void scaleFrequencyReactive(bool is_hit) {
        std::lock_guard<std::mutex> lock(mtx);
        
        if (!early_scale && is_hit) {
            std::cout << "[DVFS] case 1 : scale reactive, TTFT loss\n";
            // DVFS
        } 
        else if (early_scale && is_hit) {
            std::cout << "[DVFS] case 2 : scale early, nice.\n";
        } 
        else if (early_scale && !is_hit) {
            std::cout << "[DVFS] case 3 : scale early, Energy loss.\n";
        }
        else if (!early_scale && !is_hit){
            std::cout << "[DVFS] case 4 : didn't scale, nice.\n" ; 
        }
        
        update(is_hit);
    }
};

// golbal
PredictiveDVFS dvfsController;
std::mutex llm_mtx;
std::condition_variable llm_cv;
bool llm_request_flag = false;
std::atomic<bool> system_running(true);

// middle-ware, vision 모델에게 call 되어 llm request 결정
bool robotMiddleware(std::string vision_output) {
    // vision output 이 json 이라고 가정, object 만을 string 으로 추출
    std::string object = vision_output.json().object();
    bool decide_llm_request = false;

    switch(object) {
        case "apple":
            decide_llm_request = true;
        case "orange":
            decide_llm_request = true;
        default:
            decide_llm_request = false;
    }
    return decide_llm_request;
}

// LLM thread
void llmThreadFunc() {
    while (system_running) {
        std::unique_lock<std::mutex> lock(llm_mtx);
        llm_cv.wait(lock, [] { return llm_request_flag || !system_running; });
        
        if (!system_running) break;

        std::cout << "[LLM Thread] Starting LLM Inference...\n";
        int ret = system("echo 'Motion Plan Generated by llama-cli' > /dev/null");
        // llama cli 에 prompt 입력
        (void)ret;
        
        std::cout << "[LLM Thread] LLM Output Completed.\n";
        llm_request_flag = false;
    }
}

// --- 1 & 4. 비전 스레드 (20FPS 모사) ---
void visionThreadFunc() {
    const int target_fps = 20;
    const int frame_duration_ms = 1000 / target_fps; 
    
    for (int frame_count = 1; frame_count <= 6; ++frame_count) {
        auto start_time = std::chrono::steady_clock::now();
        std::cout << "\n=== Processing Frame " << frame_count << " ===\n";

        // 1. Controller API 단순 호출 (상태 판단은 Controller가 알아서 함)[cite: 2]
        dvfsController.scaleFrequencyEarly();

        // 2. 비전 모델 추론 (약 35ms 소요 모사 - 이 시간 동안 DVFS 지연 은닉)
        std::cout << "[Vision Thread] Vision Inference Started...\n";
        std::this_thread::sleep_for(std::chrono::milliseconds(35)); 
        
        // 3. 미들웨어 처리 및 LLM 요청 여부 결정
        bool actual_llm_request = robotMiddleware(frame_count);

        // 4. Controller API 단순 호출 (Reactive Scaling 여부 및 State 변경 위임)
        dvfsController.scaleFrequencyReactive(actual_llm_request);

        // 5. LLM 요청이 있을 경우 LLM 스레드 깨우기
        if (actual_llm_request) {
            {
                std::lock_guard<std::mutex> lock(llm_mtx);
                llm_request_flag = true;
            }
            llm_cv.notify_one();
            // llm model 에 vision 결과를 입력해야 함. 이 부분을 구현해야 함. 
            std::this_thread::sleep_for(std::chrono::milliseconds(20)); // LLM 동작 대기 모사
        }

        // 20FPS 유지를 위한 보정
        auto end_time = std::chrono::steady_clock::now();
        auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(end_time - start_time).count();
        if (elapsed < frame_duration_ms) {
            std::this_thread::sleep_for(std::chrono::milliseconds(frame_duration_ms - elapsed));
        }
    }

    system_running = false;
    llm_cv.notify_all();
}

int main() {
    std::cout << "Starting VLA Predictive-DVFS Framework...\n";

    std::thread llm_thread(llmThreadFunc);
    std::thread vision_thread(visionThreadFunc);

    vision_thread.join();
    llm_thread.join();

    std::cout << "System Terminated.\n";
    return 0;
}
